services:
  dwatch.server:
    build:
      context: ./dwatch.server
      dockerfile: Dockerfile
    image: dwatch/server
    ports:
      - 8301:8080
    container_name: dwatch-server
  dwatch.monitor:
    build:
      context: ./dwatch.monitor
      dockerfile: Dockerfile
    image: dwatch/monitor
    container_name: dwatch-monitor
    environment:
      - HEALTHCHECK_URL=http://dwatch-server:8080
    env_file:
      - keys.env