name: DWatch.Monitor

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - dwatch.monitor/**
    - .github/workflows/monitor.yml
  
  pull_request:
    branches:
    - main

    paths:
    - dwatch.monitor/**
    - .github/workflows/monitor.yml

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      needToPush: ${{ github.ref == 'refs/heads/main' }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: |- 
          linux/arm64
          linux/arm/v7
          linux/arm64/v8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: |- 
          linux/arm64
          linux/arm/v7
          linux/arm64/v8
        install: true

    - name: Login to Docker registry
      if: ${{ env.needToPush }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push multi-architecture image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: ./dwatch.monitor
    #     #push: ${{ env.needToPush }}
    #     push: true
    #     tags: |
    #       dwatch/monitor:latest
    #       dwatch/monitor:${{ github.run_number }}
    #     platforms: linux/amd64

    - name: Build and push multi-architecture image
      uses: docker/build-push-action@v6
      with:
        context: ./dwatch.monitor
        file: ./dwatch.monitor/Dockerfile.arm
        #push: ${{ env.needToPush }}
        push: true
        tags: |
          dwatch/monitor:latest-arm
          dwatch/monitor:${{ github.run_number }}-arm
        platforms: |- 
          linux/arm64
          linux/arm64v8
          linux/arm/v5
          linux/arm/v7
          linux/arm64/v8
