name: DWatch.Server

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - dwatch.server/**
    - .github/workflows/server.yml
  
  pull_request:
    branches:
    - master

    paths:
    - dwatch.server/**
    - .github/workflows/server.yml

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      needToPush: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker registry
      if: ${{ env.needToPush }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push multi-architecture image
      uses: docker/build-push-action@v5
      with:
        context: ./dwatch.server
        push: ${{ env.needToPush }}
        tags: |
          dwatch/server:latest-amd64
          dwatch/server:latest-arm64
          dwatch/server:${{ github.run_number }}-amd64
          dwatch/server:${{ github.run_number }}-arm64
        platforms: linux/amd64,linux/arm64
