FROM --platform=${BUILDPLATFORM:-linux/arm64} python as deps
WORKDIR /app

ARG BUILDPLATFORM
ARG TARGETARCH

ADD requirements.txt .
RUN python -m pip install -r requirements.txt

FROM --platform=${BUILDPLATFORM:-linux/amd64} arm64v8/python

WORKDIR /app

COPY --from=deps /app .

ADD monitor.py .

CMD ["python", "-u", "./monitor.py"] 