FROM --platform=${BUILDPLATFORM:-linux/arm64} arm64v8/python:alpine as deps
ARG BUILDPLATFORM

WORKDIR /app

ADD requirements.txt .
RUN python -m pip install -r requirements.txt

FROM deps as run

WORKDIR /app

ADD monitor.py .

CMD ["python", "-u", "./monitor.py"] 